### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by miguel-leal** [Knayder/csgo-hack#2]
Hello sir, I am new to this, I took a look to your src and I created a project to release it, I updated offsets and all ok, but when I inject my game freeze for 10 secs and finally crash .
and this the console log:
Hack injected!
801 : 600
Source: 5c247510
Destin: 6b6e16f0
Gatewa: 0

I am using this injector https://www.unknowncheats.me/forum/cs-go-releases/454734-csghost-v4-injector-integrated-vac-bypass.html
Maybe are the injection method, like load library

**Comment by miguel-leal** [comment]
UPDATE: load library and Manual map still crash.

**Comment by miguel-leal** [comment]
UPDATE V2: I debug and I found that one .lib isnt compiling so I updated that and got new console log
Hack injected!
801 : 600
Source: 5c247510
Destin: 43c2102d
Gatewa: fc0000
>>and load library and Manual map still crash

**Comment by tjatkowski** [comment]
It's just a project for my Uni. I am not going to maintain it. I can just link you sources I've used. There they explain everything you need to know.
I didn't include any logging so I can't tell what is wrong with your release.
https://www.youtube.com/watch?v=oXlOboQURy0&ab_channel=GuidedHacking
https://www.youtube.com/watch?v=No8yYrb2zfw&ab_channel=CyborgElf
https://www.youtube.com/watch?v=7QDkceeykbI&ab_channel=GuidedHacking
https://www.youtube.com/watch?v=jnUZT2gWWuE&ab_channel=GuidedHacking

Offsets for csgo:
https://github.com/frk1/hazedumper/blob/master/csgo.hpp

EDIT:
My cody is very bad, I don't recommand doing things like I did.

**Comment by miguel-leal** [comment]
Thank you for ur submmit, I'll see the vids, hope u have a nice day :)
